;;; evlogview.el --- Major mode for viewing EVInsite's log files  -*- coding: utf-8 ; lexical-binding: t -*-

;; Copyright (C) 2018 Ken-ichiro Shimojyo

;; Author:     Paul Pogonyshev <pogonyshev@gmail.com>
;; Maintainer: Paul Pogonyshev <pogonyshev@gmail.com>
;; Version:    0.9
;; Keywords:   files, tools
;; Homepage:   https://github.com/doublep/logview
;; Package-Requires: ((emacs "24.4") (datetime "0.3"))

;; This program is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License as
;; published by the Free Software Foundation, either version 3 of
;; the License, or (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see http://www.gnu.org/licenses.


;;; Commentary:

;; Logview mode provides syntax highlighting, filtering and other
;; features for various log files.  The main target are files similar
;; to ones generated by Log4j, Logback and other Java logging
;; libraries, but there is really nothing Java-specific in the mode
;; and it should work just fine with any log that follows similar
;; structure, probably after some configuration.


;;; Code:

(require 'logview)
(custom-set-variables
 '(logview-additional-level-mappings
   (quote
    (("EVLOGGER"
      (performance "PERFORM")
      (debug       "DEBUG")
      (message     "MESSAGE")
      (warning     "WARNING")
      (error      "ERROR")))))
 '(logview-additional-submodes
   (quote
    (("EVLOGGER"
      (format  "TIMESTAMP LEVEL PID[THREAD] -")
      (levels . "EVLOGGER"))))))

;; (define-derived-mode evlogview logview "EVLogView"
;;   "EVLogView mode is the extensions of logview-mode.")
;;   ;; (define-key evlogview-mode-map "M-n" 'evlogview-next-far-time-stamp))

